package zavrsnirad;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.LayoutManager;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.Clip;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Filip Božović
 */
public class _1_Menu extends javax.swing.JFrame {

    public static boolean jezik = true;
    private JLabel dobrodosliLabel;
    private JButton dugmeExit;
    private JButton dugmeNajboljiIgraci;
    private JButton dugmeNovaIgra;
    private JButton dugmeOIgrici;
    private JLabel ikonicaLabel;
    private JPanel jPanel1;
    private JLabel jezikLabel;
    private JLabel pozadina;

    /**
     * Creates new form _1_Menu
     */
    public _1_Menu() {
        if (_3_sudoku9x9.fontNivoi == null) {
            _3_sudoku9x9.podesiFont();
        }
        initComponents();
        setPozadina();
        if (_3_sudoku9x9.clipMuzika == null) {
            _3_sudoku9x9.playSound("muzika.wav");
            try {
                Thread.sleep(500L);
            } catch (InterruptedException ex) {
                Logger.getLogger(_1_Menu.class.getName()).log(Level.SEVERE, (String) null, ex);
            }
        }
        if (_3_sudoku9x9.clipMuzika.isRunning()) {
            this.ikonicaLabel.setIcon(new ImageIcon(getClass().getResource("/zavrsnirad/slike/zvukOn.png")));
        } else {
            this.ikonicaLabel.setIcon(new ImageIcon(getClass().getResource("/zavrsnirad/slike/zvukOff.png")));
        }
        if (_5_cestitamo.cestitamo
                && _3_sudoku9x9.listaClip.size() > 0) {
            for (Clip c : _3_sudoku9x9.listaClip) {
                c.close();
            }
            _3_sudoku9x9.listaClip.clear();
        }
        podesiJezik();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		this.jPanel1 = new JPanel();
		this.dugmeOIgrici = new JButton();
		this.dobrodosliLabel = new JLabel();
		this.dugmeExit = new JButton();
		this.dugmeNovaIgra = new JButton();
		this.dugmeNajboljiIgraci = new JButton();
		this.ikonicaLabel = new JLabel();
		this.jezikLabel = new JLabel();
		this.pozadina = new JLabel();
		setDefaultCloseOperation(3);
		setTitle("Meni");
		setMinimumSize(new Dimension(606, 528));
		setResizable(false);
		setSize(new Dimension(0, 0));
		getContentPane().setLayout((LayoutManager)null);
		this.jPanel1.setOpaque(false);
		this.dugmeOIgrici.setFont(_3_sudoku9x9.fontIgre2);
		this.dugmeOIgrici.setText("O igrici");
		this.dugmeOIgrici.setFocusable(false);
		this.dugmeOIgrici.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            _1_Menu.this.dugmeOIgriciActionPerformed(evt);
          }
        });
		this.dobrodosliLabel.setFont(_3_sudoku9x9.fontNaslov);
		this.dobrodosliLabel.setHorizontalAlignment(0);
		this.dobrodosliLabel.setText("Dobrodošli u Sudoku!");
		this.dugmeExit.setFont(_3_sudoku9x9.fontIgre3);
		this.dugmeExit.setText("Izađi");
		this.dugmeExit.setFocusable(false);
		this.dugmeExit.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            _1_Menu.this.dugmeExitActionPerformed(evt);
          }
        });
		this.dugmeNovaIgra.setFont(_3_sudoku9x9.fontIgre);
		this.dugmeNovaIgra.setText("Nova igra");
		this.dugmeNovaIgra.setFocusable(false);
		this.dugmeNovaIgra.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            _1_Menu.this.dugmeNovaIgraActionPerformed(evt);
          }
        });
		this.dugmeNajboljiIgraci.setFont(_3_sudoku9x9.fontIgre1);
		this.dugmeNajboljiIgraci.setText("Igrači");
		this.dugmeNajboljiIgraci.setFocusable(false);
		this.dugmeNajboljiIgraci.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            _1_Menu.this.dugmeNajboljiIgraciActionPerformed(evt);
          }
        });
		this.ikonicaLabel.setHorizontalAlignment(0);
		this.ikonicaLabel.addMouseListener(new MouseAdapter() {
        public void mousePressed(MouseEvent evt) {
            _1_Menu.this.ikonicaLabelMousePressed(evt);
          }
        });
		this.jezikLabel.setFont(_3_sudoku9x9.fontDugme);
		this.jezikLabel.setText("srp");
		this.jezikLabel.addMouseListener(new MouseAdapter() {
        public void mousePressed(MouseEvent evt) {
            _1_Menu.this.jezikLabelMousePressed(evt);
          }
        });
		GroupLayout jPanel1Layout = new GroupLayout(this.jPanel1);
		this.jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
			.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
			  .addGap(80, 80, 80)
			  .addComponent(this.jezikLabel)
			  .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, -1, 32767)
			  .addComponent(this.ikonicaLabel, -2, 32, -2)
			  .addGap(46, 46, 46))
			.addGroup(jPanel1Layout.createSequentialGroup()
			  .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
				  .addGap(175, 175, 175)
				  .addComponent(this.dugmeNajboljiIgraci, -2, 215, -2))
				.addGroup(jPanel1Layout.createSequentialGroup()
				  .addContainerGap()
				  .addComponent(this.dobrodosliLabel, -2, 564, -2))
				.addGroup(jPanel1Layout.createSequentialGroup()
				  .addGap(167, 167, 167)
				  .addComponent(this.dugmeNovaIgra, -2, 235, -2))
				.addGroup(jPanel1Layout.createSequentialGroup()
				  .addGap(198, 198, 198)
				  .addComponent(this.dugmeOIgrici, -2, 170, -2))
				.addGroup(jPanel1Layout.createSequentialGroup()
				  .addGap(232, 232, 232)
				  .addComponent(this.dugmeExit, -2, 110, -2)))
			  .addContainerGap(-1, 32767)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout
			.createParallelGroup(GroupLayout.Alignment.LEADING)
			.addGroup(jPanel1Layout.createSequentialGroup()
			  .addGap(27, 27, 27)
			  .addComponent(this.dobrodosliLabel, -2, 130, -2)
			  .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
				  .addGap(4, 4, 4)
				  .addComponent(this.dugmeNovaIgra, -2, 49, -2)
				  .addGap(18, 18, 18)
				  .addComponent(this.dugmeNajboljiIgraci, -2, 42, -2)
				  .addGap(18, 18, 18)
				  .addComponent(this.dugmeOIgrici, -2, 42, -2)
				  .addGap(18, 18, 18)
				  .addComponent(this.dugmeExit, -2, 30, -2)
				  .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 36, 32767)
				  .addComponent(this.ikonicaLabel, -2, 32, -2)
				  .addGap(32, 32, 32))
				.addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
				  .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, -1, 32767)
				  .addComponent(this.jezikLabel)
				  .addContainerGap()))));
		getContentPane().add(this.jPanel1);
		this.jPanel1.setBounds(10, 11, 584, 478);
		this.pozadina.setIcon(new ImageIcon(getClass().getResource("/zavrsnirad/slike/pozadinaKocka1.jpg")));
		getContentPane().add(this.pozadina);
		this.pozadina.setBounds(0, 0, 600, 500);
		pack();
		setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dugmeExitActionPerformed(ActionEvent evt) {
        if (_3_sudoku9x9.clipMuzika != null) {
            _3_sudoku9x9.playSound("muzika.wav", "pauza");
        }
        _3_sudoku9x9.playSound("exit1.wav");
        try {
            Thread.sleep(2100L);
        } catch (InterruptedException ex) {
            Logger.getLogger(_1_Menu.class.getName()).log(Level.SEVERE, (String) null, ex);
        }
        System.exit(0);
    }

    private void dugmeNovaIgraActionPerformed(ActionEvent evt) {
        _3_sudoku9x9.playSound("klik.wav");
        _2_Podesavanja p = new _2_Podesavanja();
        dispose();
        p.setVisible(true);
    }

    private void dugmeNajboljiIgraciActionPerformed(ActionEvent evt) {
        _3_sudoku9x9.playSound("klik.wav");
        _6_najboljiIgrac h = new _6_najboljiIgrac();
        dispose();
        h.setVisible(true);
    }

    private void dugmeOIgriciActionPerformed(ActionEvent evt) {
        _3_sudoku9x9.playSound("klik.wav");
        _7_oIgrici k = new _7_oIgrici();
        dispose();
        k.setVisible(true);
    }

    private void ikonicaLabelMousePressed(MouseEvent evt) {
        _3_sudoku9x9.playSound("klik.wav");
        if (_3_sudoku9x9.clipMuzika.isRunning()) {
            _3_sudoku9x9.playSound("muzika.wav", "pauza");
            this.ikonicaLabel.setIcon(new ImageIcon(getClass().getResource("/zavrsnirad/slike/zvukOff.png")));
        } else {
            _3_sudoku9x9.playSound("muzika.wav", "nastavi");
            this.ikonicaLabel.setIcon(new ImageIcon(getClass().getResource("/zavrsnirad/slike/zvukOn.png")));
        }
    }

    private void jezikLabelMousePressed(MouseEvent evt) {
        if (this.jezikLabel.getText().equals("srp")) {
            this.jezikLabel.setText("eng");
            jezik = false;
        } else {
            this.jezikLabel.setText("srp");
            jezik = true;
        }
        podesiJezik();
    }

    private void setPozadina() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/zavrsnirad/slike/ikonica.png")));
    }

    private void podesiJezik() {
        if (jezik) {
            this.jezikLabel.setText("srp");
            this.dugmeExit.setText("Izađi");
            this.dugmeNajboljiIgraci.setText("Igrači");
            this.dugmeNovaIgra.setText("Nova igra");
            this.dugmeOIgrici.setText("O igrici");
            this.dobrodosliLabel.setText("Dobrodošli u Sudoku!");
            setTitle("Meni");
        } else {
            this.jezikLabel.setText("eng");
            this.dugmeExit.setText("Exit");
            this.dugmeNajboljiIgraci.setText("Players");
            this.dugmeNovaIgra.setText("New game");
            this.dugmeOIgrici.setText("About game");
            this.dobrodosliLabel.setText("Welcome to Sudoku!");
            setTitle("Menu");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_1_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_1_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_1_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_1_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _1_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
