package zavrsnirad;

import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Filip Božović
 */
public class _8_uputstvo extends javax.swing.JFrame {

    private JToggleButton dugmeNazad;
    private JPanel jPanel1;
    private JLabel pozadinaLabel;

    /**
     * Creates new form _8_uputstvo
     */
    public _8_uputstvo() {
        initComponents();
        podesiJezik();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.jPanel1 = new JPanel();
     this.pozadinaLabel = new JLabel();
     this.dugmeNazad = new JToggleButton();
     setDefaultCloseOperation(3);
     setResizable(false);
     this.pozadinaLabel.setIcon(new ImageIcon(getClass().getResource("/zavrsnirad/slike/uputstvoSrp.png")));
     this.dugmeNazad.setFont(_3_sudoku9x9.fontDugme);
     this.dugmeNazad.setText("Nazad");
     this.dugmeNazad.setFocusable(false);
     this.dugmeNazad.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
             _8_uputstvo.this.dugmeNazadActionPerformed(evt);
           }
         });
     GroupLayout jPanel1Layout = new GroupLayout(this.jPanel1);
     this.jPanel1.setLayout(jPanel1Layout);
     jPanel1Layout.setHorizontalGroup(jPanel1Layout
         .createParallelGroup(GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
           .addComponent(this.pozadinaLabel)
           .addGap(0, 0, 32767))
         .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
           .addContainerGap(-1, 32767)
           .addComponent(this.dugmeNazad)
           .addGap(256, 256, 256)));
     jPanel1Layout.setVerticalGroup(jPanel1Layout
         .createParallelGroup(GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
           .addComponent(this.pozadinaLabel, -2, 589, -2)
           .addGap(0, 0, 0)
           .addComponent(this.dugmeNazad)));
     GroupLayout layout = new GroupLayout(getContentPane());
     getContentPane().setLayout(layout);
     layout.setHorizontalGroup(layout
         .createParallelGroup(GroupLayout.Alignment.LEADING)
         .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
           .addContainerGap()
           .addComponent(this.jPanel1, -2, 580, 32767)
           .addContainerGap()));
     layout.setVerticalGroup(layout
         .createParallelGroup(GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
           .addContainerGap()
           .addComponent(this.jPanel1, -2, -1, -2)
           .addContainerGap(-1, 32767)));
     pack();
     setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dugmeNazadActionPerformed(ActionEvent evt) {
        _7_oIgrici s = new _7_oIgrici();
        _3_sudoku9x9.playSound("klik.wav");
        dispose();
        s.setVisible(true);
    }

    private void podesiJezik() {
        if (_1_Menu.jezik) {
            this.pozadinaLabel.setIcon(new ImageIcon(getClass().getResource("/zavrsnirad/slike/uputstvoSrp.png")));
            this.dugmeNazad.setText("Nazad");
            setTitle("Uputstvo");
        } else {
            this.pozadinaLabel.setIcon(new ImageIcon(getClass().getResource("/zavrsnirad/slike/uputstvoEng.png")));
            this.dugmeNazad.setText("Back");
            setTitle("Instruction");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_8_uputstvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_8_uputstvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_8_uputstvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_8_uputstvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _8_uputstvo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
